version: 2
jobs:
  build:
    docker:
      - image: ishikocpp/gcc-boost:9.1.0-1.70.0
    steps:
      - checkout:
          path: /CodeSmithyIDE/CodeSmithy
      - run:
          name: Build
          command: cd /CodeSmithyIDE/CodeSmithy/Core/Makefiles/GNUmakefile && make
