version: 2
jobs:
  build:
    docker:
      - image: ishikocpp/gcc-boost:9.1.0-1.70.0
    steps:
      - run: 
          name: "Set ISHIKO_CPP and DIPLODOCUSDB environment variables and create directory"
          command: mkdir /CodeSmithyIDE && echo 'export ISHIKO_CPP="/CodeSmithyIDE"' >> $BASH_ENV \
                   && echo 'export DIPLODOCUSDB="/CodeSmithyIDE"' >> $BASH_ENV
      - run:
          name: "Checkout CodeSmithyIDE/Collections dependency"
          command: cd /CodeSmithyIDE && git clone https://github.com/CodeSmithyIDE/Collections.git
      - run:
          name: "Checkout CodeSmithyIDE/TreeDB dependency"
          command: cd /CodeSmithyIDE && git clone https://github.com/CodeSmithyIDE/TreeDB.git
      - checkout:
          path: /CodeSmithyIDE/CodeSmithy
      - run:
          name: "Build CodeSmithyIDE/Collections dependency"
          command: cd /CodeSmithyIDE/Collections/Makefiles/GNUmakefile && make
      - run:
          name: "Build CodeSmithyIDE/TreeDB dependency"
          command: cd /CodeSmithyIDE/TreeDB/Core/Makefiles/GNUmakefile && make
      - run:
          name: Build
          command: cd /CodeSmithyIDE/CodeSmithy/Core/Makefiles/GNUmakefile && make
